<a href="https://colab.research.google.com/github/yashjain-99/Projects/blob/main/Financial_Statement_Analysis_Using_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Financial Statement analysis using bert
@author : Yash Jain
https://github.com/yashjain-99/Projects

In [1]:
!pip install transformers

     |████████████████████████████████| 4.0 MB 8.3 MB/s 
     |████████████████████████████████| 596 kB 49.0 MB/s 
     |████████████████████████████████| 77 kB 9.0 MB/s 
     |████████████████████████████████| 895 kB 53.2 MB/s 
     |████████████████████████████████| 6.5 MB 64.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [2]:
from transformers import AutoTokenizer, AutoModelForMaskedLM, TFBertModel

tokenizer = AutoTokenizer.from_pretrained("bert-base-cased")

bert = TFBertModel.from_pretrained("bert-base-cased")

Downloading:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/570 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/208k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/426k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/502M [00:00<?, ?B/s]

Some layers from the model checkpoint at bert-base-cased were not used when initializing TFBertModel: ['mlm___cls', 'nsp___cls']
- This IS expected if you are initializing TFBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
All the layers of TFBertModel were initialized from the model checkpoint at bert-base-cased.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions without further training.


In [3]:
tokenizer.save_pretrained('bert_token')
bert.save_pretrained('bert_model')

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
import zipfile
import os
local_zip='/content/drive/MyDrive/Colab Notebooks/archive (4).zip'
zipref=zipfile.ZipFile(local_zip,'r')
os.mkdir('FinancialSentiment')
zipref.extractall('FinancialSentiment')
zipref.close()

In [6]:
import pandas as pd
df=pd.read_csv('/content/FinancialSentiment/data.csv')
df.head()

Sentence Sentiment
0  The GeoSolutions technology will leverage Bene...  positive
1  $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2  For the last quarter of 2010 , Componenta 's n...  positive
3  According to the Finnish-Russian Chamber of Co...   neutral
4  The Swedish buyout firm has sold its remaining...   neutral

In [7]:
df['Sentiment'].unique()

array(['positive', 'negative', 'neutral'], dtype=object)

In [8]:
df.info

<bound method DataFrame.info of                                                Sentence Sentiment
0     The GeoSolutions technology will leverage Bene...  positive
1     $ESI on lows, down $1.50 to $2.50 BK a real po...  negative
2     For the last quarter of 2010 , Componenta 's n...  positive
3     According to the Finnish-Russian Chamber of Co...   neutral
4     The Swedish buyout firm has sold its remaining...   neutral
...                                                 ...       ...
5837  RISING costs have forced packaging producer Hu...  negative
5838  Nordic Walking was first used as a summer trai...   neutral
5839  According shipping company Viking Line , the E...   neutral
5840  In the building and home improvement trade , s...   neutral
5841  HELSINKI AFX - KCI Konecranes said it has won ...  positive

[5842 rows x 2 columns]>

In [9]:
sentences = []
labels = []
for i,j in zip(df['Sentence'],df['Sentiment']):
  sentences.append(i)
  labels.append(j)

In [10]:
m=0
for i in sentences:
  m=max(m,len(i))

In [11]:
for i in sentences:
  if len(i)==m:
    print(i)

Supported Nokia phones include : N96 , N95-8GB , N95 , N93-N931 , N92 , N85 , N82 , N81 , N80 , N79 , N78 , N77 , N76 , N75 , N73 , N72 , N71 , E90 , E71 , E70 , E66 , E65 , E62 , E61-E61i , E60 , E51 , E50 , Touch Xpress 5800 , 6220 Classic , 6210 Navigator , 6120 Classic , 6110 Navigator , 5700 , 5500 , 5320XM .


In [12]:
m

315

In [13]:
for i in range(len(labels)):
  if labels[i]=='neutral':
    labels[i]=float(0)
  elif labels[i]=='positive':
    labels[i]=float(1)
  else:
    labels[i]=float(2)

In [14]:
lb=tf.keras.utils.to_categorical(labels,num_classes=3)

In [15]:
lb

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]], dtype=float32)

In [16]:
x_train=tokenizer(
    text=sentences,
    add_special_tokens=True,
    max_length=m,
    truncation=True,
    padding=True,
    return_tensors='tf',
    return_token_type_ids=False,
    return_attention_mask=True,
    verbose = True
)

In [17]:
x_train['attention_mask'][1]

<tf.Tensor: shape=(155,), dtype=int32, numpy=
array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0], dtype=int32)>

In [18]:
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.initializers import TruncatedNormal
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras.metrics import CategoricalAccuracy
from tensorflow.keras.utils import to_categorical

In [19]:
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense

input_ids = Input(shape=(155,), dtype=tf.int32, name="input_ids")
input_mask = Input(shape=(155,), dtype=tf.int32, name="attention_mask")
# embeddings = dbert_model(input_ids,attention_mask = input_mask)[0]


embeddings = bert(input_ids,attention_mask = input_mask)[0] #(0 is the last hidden states,1 means pooler_output)
out = tf.keras.layers.GlobalMaxPool1D()(embeddings)
out = Dense(128, activation='relu')(out)
out = tf.keras.layers.Dropout(0.1)(out)
out = Dense(32,activation = 'relu')(out)

y = Dense(3,activation = 'sigmoid')(out)
    
model = tf.keras.Model(inputs=[input_ids, input_mask], outputs=y)
model.layers[2].trainable = True

In [20]:
optimizer = Adam(
    learning_rate=5e-05,
    epsilon=1e-08,
    decay=0.01,
    clipnorm=1.0)
loss =CategoricalCrossentropy(from_logits = True)
metric = CategoricalAccuracy('balanced_accuracy'),
model.compile(
    optimizer = optimizer,
    loss = loss, 
    metrics = metric)

In [21]:
class myCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs={}):
    if(logs.get('balanced_accuracy')>0.99):
      print("\nReached 99.0% accuracy so cancelling training!")
      self.model.stop_training = True

In [22]:
from tensorflow.keras.callbacks import EarlyStopping

In [23]:
callback_early_stopping = EarlyStopping(monitor='balanced_accuracy',
                                        patience=3, verbose=1)

In [24]:
callbacks = myCallback()
train_history = model.fit(
    x ={'input_ids':x_train['input_ids'],'attention_mask':x_train['attention_mask']} ,
    y = lb,
  epochs=10,
  callbacks=[callbacks, callback_early_stopping]
)

Epoch 1/10


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


183/183 [==============================] - 222s 1s/step - loss: 0.6361 - balanced_accuracy: 0.7083
Epoch 2/10
183/183 [==============================] - 185s 1s/step - loss: 0.3664 - balanced_accuracy: 0.8290
Epoch 3/10
183/183 [==============================] - 185s 1s/step - loss: 0.2604 - balanced_accuracy: 0.8646
Epoch 4/10
183/183 [==============================] - 185s 1s/step - loss: 0.2089 - balanced_accuracy: 0.8819
Epoch 5/10
183/183 [==============================] - 185s 1s/step - loss: 0.1887 - balanced_accuracy: 0.8920
Epoch 6/10
183/183 [==============================] - 185s 1s/step - loss: 0.1694 - balanced_accuracy: 0.8980
Epoch 7/10
183/183 [==============================] - 185s 1s/step - loss: 0.1620 - balanced_accuracy: 0.9023
Epoch 8/10
183/183 [==============================] - 185s 1s/step - loss: 0.1527 - balanced_accuracy: 0.9059
Epoch 9/10
183/183 [==============================] - 185s 1s/step - loss: 0.1509 - balanced_accuracy: 0.9011
Epoch 10/10
183/183 [

In [25]:
model.save("finsent.h5")

In [26]:
test="Yogabar registers 150% growth in revenue in FY22; online channels account for 50% of the overall sales"

In [36]:
x_test = tokenizer(
    text=test,
    add_special_tokens=True,
    max_length=155,
    truncation=True,
    padding='max_length', 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)

In [38]:
predicted_raw = model.predict({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']})

In [39]:
np.argmax(predicted_raw, axis = 1)

array([1])

1 implies positive news

In [40]:
test="Rupee likely to depreciate on strong dollar, risk aversion in markets; USDINR pair to trade in this range"
x_test = tokenizer(
    text=test,
    add_special_tokens=True,
    max_length=155,
    truncation=True,
    padding='max_length', 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)
predicted_raw = model.predict({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']})
np.argmax(predicted_raw, axis = 1)

array([2])

2 implies negative news

In [41]:
test="TCS, Adani Green Energy, Hathway, Delta Corp, Nestle, GM Breweries, Godrej Industries stocks in focus"
x_test = tokenizer(
    text=test,
    add_special_tokens=True,
    max_length=155,
    truncation=True,
    padding='max_length', 
    return_tensors='tf',
    return_token_type_ids = False,
    return_attention_mask = True,
    verbose = True)
predicted_raw = model.predict({'input_ids':x_test['input_ids'],'attention_mask':x_test['attention_mask']})
np.argmax(predicted_raw, axis = 1)

array([0])

0 implies neutral news

Task left:
1. Automate it using selenium in which we will just enter stock name and it will use internet sources to gather recent news, based on which it will predict sentiment of that stock